//tealium universal tag - utag.3681 ut4.0.202210271833, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;window.TMS.debug=window.TMS.debug||[];window.dataLayer=window.dataLayer||[];var gtag=function(){window.dataLayer.push(arguments);}
try{function getGTAGevents(){var eventName,_utag_data=utag.data,gtagevents={};var prop;for(prop in _utag_data){if(TMS.util.hasOwn(_utag_data,prop)&&prop.toString().indexOf("vendor_gtag_event")>=0&&_utag_data[prop]=="1"){eventName=prop.replace("vendor_gtag_event_","");gtagevents[eventName]=_utag_data[prop];}}
return gtagevents;}
function isEmpty(obj){var key;for(key in obj){if(obj.hasOwnProperty(key))
return false;}
return true;}
if(isEmpty(getGTAGevents())){utag.data['vendor_gtag_eventlist']={'view':1,'link':1,'click':1};}else{utag.data['vendor_gtag_eventlist']=getGTAGevents();}
function Event(eventType,sendToData,customVars,b){var eventConfigJSON;var eventConfig={"allow_custom_scripts":true};if(customVars){var custVars=getCustomVars(customVars,b);var custParams=getCustomParams('dc_custParam_',b);var custParamsObj={};for(i=0;i<custVars.length;i++){eventConfig["u"+custVars[i][1]]=custVars[i][0];}
if(custParams.length>0){for(i=0;i<custParams.length;i++){custParamsObj[custParams[i][1]]=custParams[i][0];}
eventConfig['dc_custom_params']=custParamsObj;}}
eventConfig["send_to"]=sendToData;gtag("event",eventType,eventConfig);}
function viewEvent(sendToData,customVars,b){Event("page_view",sendToData,customVars,b)}
function conversionEvent(sendToData,customVars,b){Event("conversion",sendToData,customVars,b)}
function setDeveloperId(){Event("set",{"developer_id.dYmQxMT":true});}
function getCustomVars(searchTearm,b){var custVarPrefix="vendor_gtag_"+searchTearm;var custVarId;var custVars=[];var prop;for(prop in b){if(b.hasOwnProperty(prop)&&prop.toString().indexOf(searchTearm)>=0&&typeof b[prop]!=='undefined'&&b[prop]!==""&&b[prop].toString().indexOf('undefined')==-1){custVarId=prop.replace(custVarPrefix,'');custVars.push([b[prop],custVarId]);}}
if(String(b.vendor_gtag_u_dimension_map_enabled)=="1"){Object.keys(u.data).filter(function(a){return/^u([1-9][0-9]?|100)/.test(a)}).forEach(function(a){custVars.push([u.data[a],a.replace("u","")])});}
return custVars}
function getCustomParams(searchTearm,b){var custParamPrefix=searchTearm;var custParams=[];var prop;for(prop in b){if(b.hasOwnProperty(prop)&&prop.toString().indexOf(searchTearm)>=0&&typeof b[prop]!=='undefined'&&b[prop]!==""&&b[prop].toString().indexOf('undefined')==-1){custParamKey=prop.replace(custParamPrefix,'');custParams.push([b[prop],custParamKey]);}}
return custParams;}
u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};}catch(e){window.TMS.debug.push({"message":"Error with eventlist or event methods","error":e});}
u.ev=utag.data.vendor_gtag_eventlist||{'view':1,'link':1};u.initialized=u.initialized||false;u.map={"vender_gtag_floodlight_config_id":"floodlight_config_id","vendor_gtag_dc_conversion_settings":"dc_conversion_settings","vender_gtag_adwords_config_id":"adwords_config_id","vendor_gtag_aw_conversion_settings":"aw_conversion_settings","vendor_gtag_organic_exclusion":"os_exclusion","vendor_gtag_organic_config_id":"os_config_id","vendor_gtag_organic_engines":"os_engines","_sm_3681_8":"u40","tealium_visitor_id":"u41","vendor_gtag_remarketing":"remarketing","vendor_gtag_base_url":"base_url","vendor_gtag_enable_tcf_support":"enable_tcf_support","vendor_gtag_developer_id":"developer_id","vendor_gtag_data_layer_name":"data_layer_name","vendor_gtag_cross_track_domain":"cross_track_domain","vendor_gtag_external_id":"config.user_id"};u.extend=[function(a,b){try{b['_sm_3681_8']=(function(c,r){return r.test(c)?c.match(r)[2]:undefined})(document.cookie,/AMCV_(.*?)MCMID%7C(.*?)%7C/);}catch(e){utag.DB(e);}},function(a,b){try{if(1){try{var dc=utag.data["vend_gdc"];var aw=utag.data["vend_gaw"];if(dc){b['vendor_gtag_dc_conversion_settings']=((TMS.util.check.isDefined(b['vendor_gtag_dc_conversion_settings'])&&b['vendor_gtag_dc_conversion_settings']!=""))?(b['vendor_gtag_dc_conversion_settings']+","+dc.join(",")):dc.join(",");}
if(aw){b['vendor_gtag_aw_conversion_settings']=((TMS.util.check.isDefined(b['vendor_gtag_aw_conversion_settings'])&&b['vendor_gtag_aw_conversion_settings']!=""))?(b['vendor_gtag_aw_conversion_settings']+","+aw.join(",")):aw.join(",");}}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['vendor_gtag_base_url']='';b['vendor_gtag_remarketing']='1';b['vendor_gtag_enable_tcf_support']='0';b['vendor_gtag_developer_id']='0';b['vendor_gtag_data_layer_name']='';b['vendor_gtag_external_id']=b['tealium_visitor_id']}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"base_url":"https://www.googletagmanager.com/gtag/js?id=","remarketing":"","data_layer_name":"","cross_track_domains":"","developer_id":0,"enable_tcf_support":0,"rmkt":{},"config":{},"event_data":{"items":[]},"event":[],"custom":{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};var params=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.map_func(e[f].split("."),u.data,b[d]);}}}
if(!u.initialized){var enabledProducts=[],tagPrefix,globalSnippetProducts="",globalSnippetId=null,snippetIdFound=false,multipleIds,tagExtension='',prop,propName,engines;function runDCConfig(dcloopConfiguration){var dc_activity_group_tagstringloop=dcloopConfiguration[0],dc_activity_tagstringloop=dcloopConfiguration[1],dc_counting_methodloop=dcloopConfiguration[2];var sendData='DC-'+u.data.floodlight_config_id+'/'+dc_activity_group_tagstringloop+'/'+dc_activity_tagstringloop+'+'+dc_counting_methodloop;conversionEvent(sendData,'dc_custvar',b);}
function runAWConfig(multipleEvents){for(var i=0;i<multipleEvents.length;i++){sendData='AW-'+multipleEvents[i];conversionEvent(sendData,null,b);}}
if(u.data.enable_tcf_support){window["gtag_enable_tcf_support"]=(u.data.enable_tcf_support&&u.data.enable_tcf_support.toString()=="1");}
if(u.data.data_layer_name){u.data.base_url=u.data.base_url+"&l="+u.data.data_layer_name;}
for(prop in u.data){if(u.data.hasOwnProperty(prop)&&prop.toString().indexOf('_config_id')>=0&&typeof u.data[prop]!=='undefined'&&u.data[prop]!==""){propName=prop.toString();if(propName.indexOf('floodlight')>=0){tagPrefix="DC";}else if(propName.indexOf('adwords')>=0){tagPrefix="AW";}else if(propName==='os_config_id'){tagPrefix="DC";engines={};var x;u.data['os_engines'].split('|').forEach(function(element){x=element.split(':');x[0]=x[0].replace(/\s+/g,"");x[1]=x[1].replace(/\s+/g,"");engines[x[0]]=x[1];});u.data.config["dc_natural_search"]={'exclusion_parameters':u.data['os_exclusion'],'engines':engines};}else{tagPrefix=""}
if(TMS.util.check.isString(u.data.conversion_cookie_prefix)){u.data.config.conversion_cookie_prefix=u.data.conversion_cookie_prefix;}
if(u.data[prop].indexOf("|")>0){multipleIds=u.data[prop]=u.data[prop].split("|");for(i=0;i<multipleIds.length;i++){gtag("config",tagPrefix+'-'+multipleIds[i],u.data.config);}
if(!snippetIdFound){globalSnippetId=tagPrefix+"-"+multipleIds[i];snippetIdFound=true;}}else{gtag("config",tagPrefix+'-'+u.data[prop],u.data.config)
if(!snippetIdFound){globalSnippetId=tagPrefix+"-"+u.data[prop];snippetIdFound=true;}}}}
gtag("js",new Date());if(u.data.developer_id&&u.data.developer_id.toString()==="1"){setDeveloperId();}
if(globalSnippetId){var gtagScruptUrl=u.data.base_url+globalSnippetId;var gtagScript=document.createElement('script');gtagScript.src=gtagScruptUrl;document.getElementsByTagName('head')[0].appendChild(gtagScript);if(!!u.data.cross_track_domains){gtag("set","linker",{domains:u.data.cross_track_domains.split(","),accept_incoming:true});}
if(u.data.remarketing&&u.data.remarketing.toString()==="1"&&u.data.adwords_config_id){if((u.data.adwords_config_id.constructor===Array)&&(u.data.adwords_config_id.length>1)){var sendData=u.data.adwords_config_id.map(function(id){return"AW-"+id;});viewEvent(sendData)}else{sendData='AW-'+u.data.adwords_config_id;viewEvent(sendData)}}
if(u.data.dc_conversion_settings&&u.data.floodlight_config_id){if((TMS.util.check.isArray(u.data.dc_conversion_settings)&&u.data.aw_conversion_settings.length>0)||u.data.dc_conversion_settings.indexOf(",")>0){var dcloop=TMS.util.check.isArray(u.data.dc_conversion_settings)?u.data.dc_conversion_settings:u.data.dc_conversion_settings.split(",");var dcloopConfiguration;for(var j=0;j<dcloop.length;j++){runDCConfig(dcloop[j].split("|"));}}else{var conversionConfiguration=u.data.dc_conversion_settings.split("|");runDCConfig(conversionConfiguration);}}
if(u.data.aw_conversion_settings&&u.data.adwords_config_id){var sendData;if(u.data.aw_conversion_settings.indexOf("|")>0){runAWConfig(u.data.aw_conversion_settings.split("|"))}else if(u.data.aw_conversion_settings.indexOf(",")>0){runAWConfig(u.data.aw_conversion_settings.split(","))}else if(TMS.util.check.isArray(u.data.aw_conversion_settings)&&u.data.aw_conversion_settings.length>0){runAWConfig(u.data.aw_conversion_settings)}else{sendData='AW-'+u.data.aw_conversion_settings;conversionEvent(sendData);}}
}
}
}};utag.o[loader].loader.LOAD(id);})("3681","hsbc.uk-rbwm");}catch(error){utag.DB(error);}
