//tealium universal tag - utag.3651 ut4.0.202207272022, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;window.TMS.debug=window.TMS.debug||[];if(utag===undefined){utag={};}
if(utag.ut===undefined){utag.ut={};}
u.ev={'view':1};u.initialized=u.initialized||false;u.map={"excluded_exit_domains":"excluded_exit_domains","aem_whitelist_domains":"whitelisted_domains"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
(function(){var Evnt=window.Evnt={addE:function(element,type,hand){if(element.addEventListener){element.addEventListener(type,hand,false);}else if(element.attachEvent){element.attachEvent('on'+type,hand);}else{element['on'+type]=hand;}},removeE:function(element,type,hand){if(element.removeEventListener){element.removeEventListener(type,hand,false);}else if(element.detachEvent){element.detachEvent('on'+type,hand);}else{element['on'+type]=null;}}};var ct;var Util=Util||{data:null,merge:function(aa,bb){for(var k in aa){if(aa.hasOwnProperty(k)&&typeof aa[k]!="undefined"){bb[k]=aa[k];}}
return bb;},check:{"isArray":function(x){return Object.prototype.toString.call(x)=="[object Array]";},"isObj":function(x){return Object.prototype.toString.call(x)=="[object Object]";},"isString":function(x){return Object.prototype.toString.call(x)=="[object String]";},"isFunc":function(x){return Object.prototype.toString.call(x)=="[object Function]";}},extend:function(subC,supC){var F=function(){};F.prototype=supC.prototype;subC.prototype=new F();subC.prototype.constructor=subC;subC.supC=supC.prototype;if(supC.prototype.constructor==Object.prototype.constructor){supC.prototype.constructor=supC;}},clone:function(obj){function F(){}
F.prototype=obj;return new F;},aug:function(rClass,gClass){if(arguments[2]){for(var i=2,len=arguments.length;i<len;i++){rClass.prototype[arguments[i]]=gClass.prototype[arguments[i]];}}else{for(mn in gClass.prototype){if(!rClass.prototype[mn]){rClass.prototype[mn]=gClass.prototype[mn];}}}},hasOP:function(par,attr){var hasOwnProp={}.hasOwnProperty;return hasOwnProp.call(par,attr);},extender:{status:false,xtnd:null,check:function(){var x=window.xtndr;if(Object.prototype.toString.call(x)=="[object Function]"){this.status=true;this.xtnd=x;}},tryExt:function(){try{Util.extender.check();if(Util.extender.status){return Util.extender.xtnd;}}catch(err){if(utag.data['ut.env']!="prod"){console.log(err);}}}},externalLinkConfig:function(aa){var config=window.dpwsExternalLinkConfiguration,i,len,res=false;for(i=0,len=config.whitelist.length;i<len;i++){if(new RegExp(config.whitelist[i]).test(aa)==true){res=true;break;}}
for(var arr in config.blacklist){if(config.blacklist.hasOwnProperty(arr)&&Object.prototype.toString.call(config.blacklist[arr])=="[object Array]"){for(i=0,len=config.blacklist[arr].length;i<len;i++){if(new RegExp(aa).test(config.blacklist[arr][i])){res=false;break;}}}}
return res;},getAttr:function(f,attr){var tar=f.target||f.srcElement,parents=tar.parentNode,res,i,len;if(tar.attributes&&tar.attributes[attr]){res={found:f,tar:tar,val:tar.attributes};this.data=res;}else{while(parents!=null){if(parents.attributes&&parents.attributes[attr]!=undefined&&parents.attributes.length>0){res={found:parents,tar:parents,val:parents.attributes};this.data=res;break;}
else{res=false;}
parents=parents.parentNode;}}
return res;},testAttr:function(e,t,d){if(!e){return false;}
var defaultValue=d||undefined;return typeof e[t]!="undefined"?{value:e[t].nodeValue,obj:e[t]}:defaultValue;}};function Cook(){}
Cook.prototype.setCookie=function(pid){var p=pid!=undefined?"|"+pid:"",domain=this.getCookieDomain();document.cookie="hsbcclkprev="+encodeURIComponent(utag.data.page_name+p)+";secure;path=/; domain="+domain+"";utag_data['cp.hsbcclkprev']=encodeURIComponent(utag.data.page_name+p);};Cook.prototype.getCookie=function(){return utag_data['cp.hsbcclkprev'];};Cook.prototype.getCookieDomain=function(){var result;if(TMS&&TMS.util&&TMS.util.getCookieDomain){result=TMS.util.getCookieDomain()}else{result=(function(host){var h=host.split("."),i=(/\.co|\.com|\.|\.org\.|\.edu\.|\.net\.|\.asn\.|\...\.jp$/.test(host))?3:2;return h.slice(h.length-i).join(".");})(window.location.hostname)}
return result;};Cook.prototype.removeCookie=function(cp){var domain=this.getCookieDomain();document.cookie=cp+"=;secure;path=/;expires=Thu, 18 Dec 1980 12:00:00 UTC; domain="+domain+"";utag_data['cp.hsbcclkprev']=null;try{delete utag_data['cp.hsbcclkprev'];}catch(e){}};function DataLayer(){this.data={};}
DataLayer.prototype=Util;DataLayer.prototype.setDataLayer=function(o,p,t){var data={dl:{page_url:o,page_name:o.replace(/^http(?:s)?(?:\:\/{2})?/,"").replace(/\//g,':').replace(/:$/,''),pid_content:p.pid.value,click_content:p.pid.value,promotion_content:p.pid.value,vam_event:p.act.value||'clickthrough',click_event:'internal_promotion'},dlctc:{page_url:window.location.pathname,page_name:utag.data.page_name||('pws'+window.location['pathname'].replace(/\//g,':').replace(/-/g,' ').replace(/:$/,'')),event_content:o.replace(/tel:/g,'HSBC# '),event_action:'click-to-call',event_category:'content'}};return data[t];};DataLayer.prototype.setEvent=function(a,promo,e){if(/\//g.test(a.value)&&promo.url!=undefined){this.setDataLayer(a.value,promo,"dl")
Util.extender.tryExt();if(!Util.externalLinkConfig(a)&&promo.tar.value!=="_blank"){}}else if(/tel\:/i.test(a.value)&&promo.url!=undefined){this.setDataLayer(a.value,promo,"dlctc");Util.extender.tryExt();}};function Attr(){this.data={};}
Attr.prototype=Util.clone(Util);Attr.prototype.checkAttr=function(e){var d={'url':this.testAttr(e,'href'),'tar':this.testAttr(e,'target'),'com':this.testAttr(e,'data-event-component'),'nam':this.testAttr(e,'data-event-name'),'res':true};return d;};Attr.prototype.getData=function(v,r){var i,len,res,ar={};this.data.keys=[];if(typeof r!='undefined'&&this.check.isArray(r)){for(i=0,len=r.length;i<=len;len--){res=this.data[v][r[len]];if(typeof res!="undefined"){ar[r[len]]=res;this.data.keys.push(r[len]);}}
return ar;}else{return this.data[v];}};Attr.prototype.setData=function(v){this.data.v=this.data.v||{};this.merge(v,this.data.v);};function CT(){this.data={};}
Util.extend(CT,Cook);Util.aug(CT,Attr);CT.prototype.buildDataString=function(s,l){var gd=this.getData(s,l);var i,len,ret="",res;for(i=0,len=this.data.keys.length;i<len;i++){res=gd[this.data.keys[i]];if(Util.check.isObj(res)&&Util.hasOP(res,"value")){ret+=res.value+"|";}else if(Util.check.isString(res)){ret+=res+"|";}else{}}
return ret.replace(/\|$/,"");};CT.prototype.init=function(){try{window.utag_data["event_clk"]=this.getCookie("hsbcclkprev");if(typeof b!='undefined'){b["event_clk"]=window.utag_data["event_clk"]};if(typeof window.utag_data["event_clk"]!='undefined'){window.sessionStorage.setItem('s_dmdbase',window.utag_data["event_clk"]);window.s=window.s||{};window.s.eVar28=window.utag_data["event_clk"];window.s.prop19=window.utag_data["event_clk"];if(utag.data['ut.env']!='prod'){console.log("clk_event >> "+window.utag.data["event_clk"])};}}catch(e){if(utag.data['ut.env']!='prod'){console.error("clk_event >> "+e)};}finally{this.removeCookie("hsbcclkprev");window.sessionStorage.removeItem('s_dmdbase');}};if(!!window.clkev===false){function clickEvent(e){var pid,href,attr=new Attr();var getp=Util.getAttr(e,"data-event-component"),links=(getp!=false)?attr.checkAttr(getp.val):false;var list=["nam","com","pid","act"];if(e.type=="click"&&links.res){var linkType=links.url||"Button";if(!linkType=="Button"){e.preventDefault();e.stopPropagation();}
ct.setData(links);ct.setCookie(ct.buildDataString('v',list));}else if(e.type=="click"&&!links.res){}else{}}
Evnt.addE(document,'click',function(e){try{clickEvent(e);}catch(error){if(utag.data['ut.env']!='prod'){console.log(error);}}
try{if(window.xtndr){Util.extender.tryExt(e);}}catch(error){if(utag.data['ut.env']!='prod'){console.log(error);}}});window.clkev=true;}
var links=document.getElementsByTagName('a');for(var i=0;i<links.length;i++){links[i].addEventListener("click",function(e){handleLinkClickEvent(e,this);});}
var documentTypes=[".pdf",".doc",".xml",".txt",".exe",".zip",".wav",".mp3",".mov",".mpg",".avi",".wmv",".pdf",".doc",".docx",".xls",".xlsx",".ppt",".pptx"];var errorLog=[];function handleLinkClickEvent(ev,link){var isDownload=false,isExitLink=false,isExcludedDomain=false,isNewTabLink=(link.target&&link.target.toLowerCase()&&link.target.toLowerCase()=="_blank");function delayRedirect(){try{if(link.href&&/^[^#]/.test(link.href)&&!isNewTabLink){ev.preventDefault();ev.stopPropagation();setTimeout(function(){window.location.href=link.href;},500);}}catch(error){errorLog.push("Delay Redirect handler: "+error.message);window.TMS.debug.push(error);}}
function triggerTracking(type,errorLog){try{var linkType=type;TMS.trackEvent({"page_name":b.page_name,"page_url":b.page_url,"event_action":linkType,"event_content":link.href,"event_subcategory":errorLog})}catch(error){window.TMS.debug.push(error);}}
if(link.href[0]!="/"&&link.href.indexOf(TMS.util.getCookieDomain())==-1){try{isExitLink=true;var excludedDomains=u.data["excluded_exit_domains"]||[];if(excludedDomains&&excludedDomains.length>0){for(var i=0;i<excludedDomains.length;i++){if(link.href.indexOf(excludedDomains[i])>-1){isExitLink=false;break;}}}}catch(error){errorLog.push("Exit Link Check: "+error.message);window.TMS.debug.push(error);}}
for(var i=0;i<documentTypes.length;i++){try{if(link.href.indexOf(documentTypes[i])>-1){isDownload=true;break;}}catch(error){errorLog.push("Download Link Check: "+error.message);window.TMS.debug.push(error);}}
if(isDownload){triggerTracking("download");}
if(!isDownload&&isExitLink){try{var whitelisted=false;var whitelistedDomainsFallback=u.data["whitelisted_domains"]||"";var whitelistedDomains=window.dpwsExternalLinkConfiguration?window.dpwsExternalLinkConfiguration.whitelist:whitelistedDomainsFallback;triggerTracking("exit");if(whitelistedDomains){for(var i=0;i<whitelistedDomains.length;i++){if(link.href.indexOf(whitelistedDomains[i])>-1){whitelisted=true;break;}}}
if(whitelisted&&!isNewTabLink){delayRedirect();}}catch(error){errorLog.push("Exit Link Handler: "+error.message);window.TMS.debug.push(error);}}
if(utag.data['ut.env']!='prod'&&errorLog.length>0){triggerTracking("error",errorLog.toString().replace(/undefined/g,"notdefined"));}}
function pageload(){ct=new CT();ct.init();return ct;}
pageload();utag_data["vendor_clicktracking_triggered"]="version: "+b["tmsLibVer_clicktracking"];})();}};utag.o[loader].loader.LOAD(id);})("3651","hsbc.uk-rbwm");}catch(error){utag.DB(error);}
