//tealium universal tag - utag.3731 ut4.0.202211141714, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;u.ev={"view":1};u.scriptrequested=u.scriptrequested||false;u.map={"global_persist_parameter":"persist_parameter","global_persist_classes":"persist_classes","global_persist_ids":"persist_ids","global_persist_key":"persist_key","global_persist_page_trigger":"page_trigger"};u.extend=[function(a,b){try{if(b['dom.query_string'].toString().indexOf('hd_token')>-1){b['global_persist_classes']='';b['global_persist_parameter']='hd_token';b['global_persist_key']='hd_token';b['global_persist_ids']='pp_tools_button_3,pp_tools_button_1'}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:3731");utag.DB(b);var c,d,e,f;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB("send:3731:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:3731:MAPPINGS");utag.DB(u.data);if(!u.scriptrequested){var tag=typeof b!=='undefined'?b:utag&&utag_data;(function(b,u){var Util={isString:function(x){return Object.prototype.toString.call(x)==="[object String]"},isArray:function(x){return Object.prototype.toString.call(x)==="[object Array]"},param:function(l){var aa=!/\?/.test(l)?"?":'',bb=(aa==''&&/\&/.test(l))?'&':''
cc=aa||bb||"&";return cc},convertArray:function(l){return Util.isArray(l)?l:l.split(',');},excludeAnchor:function(l){return/^\#./.test(l)}},d={id:b['qp.'+u.data['persist_key']]||b['qp.cid']||b['qp.pid'],classes:u.data["persist_classes"],ids:u.data["persist_ids"],parameter:u.data["persist_parameter"]||"mkt="};if(d.id&&u.data.page_trigger=="1"){(function(d){var href=document.getElementsByTagName('a')||document.anchor,len,i,ii,n,url;d.classes=(typeof d.classes!=="undefined")?Util.convertArray(d.classes):0;d.ids=(typeof d.ids!=="undefined")?Util.convertArray(d.ids):0;if(d.classes||d.ids){for(n=href.length-1;n>=0;n--){for(i=d.classes.length-1;i>=0;i--){if((!href[n].attributes&&!href[n].attributes.className)||Util.excludeAnchor(href[n].attributes['href']&&href[n].attributes['href'].value)||href[n].attributes["data-persisted"]){break}
if(href[n].className&&href[n].className.indexOf(d.classes[i])!=-1){url=href[n].attributes['href']&&href[n].attributes['href'].value;href[n].attributes['href'].value=url+Util.param(url)+d.parameter+"="+encodeURIComponent(d.id);href[n].attributes["data-persisted"]="1";}}
for(ii=d.ids.length-1;ii>=0;ii--){if((!href[n].attributes&&!href[n].attributes.id)||Util.excludeAnchor(href[n].attributes['href']&&href[n].attributes['href'].value)||href[n].attributes["data-persisted"]){break}
if(href[n].id&&href[n].id.indexOf(d.ids[ii])!=-1){url=href[n].attributes['href']&&href[n].attributes['href'].value;href[n].attributes['href'].value=url+Util.param(url)+d.parameter+"="+encodeURIComponent(d.id);href[n].attributes["data-persisted"]="1";}}}}}(d))}
function getLinkDomain(link){try{var url=(new URL(link));var linkDomain=url.hostname;linkDomain=linkDomain.replace("www.","");return linkDomain;}
catch{console.log("link not in correct format");}}
function crossDomain(){try{var links=document.getElementsByTagName('a')||document.anchor;var currentDomain=document.domain;var sid=utag_data["tealium_session_id"]||"";var vid=utag_data["tealium_visitor_id"]||"";var param;var profile="_"+utag_data["ut.profile"].substring(0,2);var linkDomain;if(sid&&vid){if(vid.indexOf(profile)>-1){vid=vid.replace(profile,"");}
param="vid="+vid+profile+"&"+"sid="+sid;}
if(param){try{currentDomain=currentDomain.replace("www.","");for(var i=0;i<links.length;i++){if(links[i].href[0]!="/"&&links[i].href[0]!=""){linkDomain=getLinkDomain(links[i].href);if(linkDomain&&linkDomain!==currentDomain&&linkDomain.indexOf("hsbc.")>-1&&(linkDomain.indexOf(currentDomain)==-1&&currentDomain.indexOf(linkDomain)==-1)){links[i].href=links[i].href+Util.param(links[i].href)+param;console.log(links[i]);}}}}
catch{console.log("domain not in correct format");}}}
catch(e){TMS.debug.push(e)}}
var configLinksTimeout=setTimeout(crossDomain,500);}(tag,u))}
utag.DB("send:3731:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("3731","hsbc.uk-rbwm"));}catch(error){utag.DB(error);}