//tealium universal tag - utag.3676 ut4.0.202207272023, Copyright 2022 Tealium.com Inc. All Rights Reserved.
if(typeof JSON!=='object'){JSON={};}
(function(){'use strict';var rx_one=/^[\],:{}\s]*$/,rx_two=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,rx_three=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,rx_four=/(?:^|:|,)(?:\s*\[)+/g,rx_escapable=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,rx_dangerous=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;function f(n){return n<10?'0'+n:n;}
function this_value(){return this.valueOf();}
if(typeof Date.prototype.toJSON!=='function'){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+'-'+
f(this.getUTCMonth()+1)+'-'+f(this.getUTCDate())+'T'+f(this.getUTCHours())+':'+f(this.getUTCMinutes())+':'+
f(this.getUTCSeconds())+'Z':null;};Boolean.prototype.toJSON=this_value;Number.prototype.toJSON=this_value;String.prototype.toJSON=this_value;}
var gap,indent,meta,rep;function quote(string){rx_escapable.lastIndex=0;return rx_escapable.test(string)?'"'+string.replace(rx_escapable,function(a){var c=meta[a];return typeof c==='string'?c:'\\u'+('0000'+a.charCodeAt(0).toString(16)).slice(-4);})+'"':'"'+string+'"';}
function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==='object'&&typeof value.toJSON==='function'){value=value.toJSON(key);}
if(typeof rep==='function'){value=rep.call(holder,key,value);}
switch(typeof value){case'string':return quote(value);case'number':return isFinite(value)?String(value):'null';case'boolean':case'null':return String(value);case'object':if(!value){return'null';}
gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==='[object Array]'){length=value.length;for(i=0;i<length;i+=1){partial[i]=str(i,value)||'null';}
v=partial.length===0?'[]':gap?'[\n'+gap+partial.join(',\n'+gap)+'\n'+mind+']':'['+partial.join(',')+']';gap=mind;return v;}
if(rep&&typeof rep==='object'){length=rep.length;for(i=0;i<length;i+=1){if(typeof rep[i]==='string'){k=rep[i];v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}else{for(k in value){if(Object.prototype.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?': ':':')+v);}}}}
v=partial.length===0?'{}':gap?'{\n'+gap+partial.join(',\n'+gap)+'\n'+mind+'}':'{'+partial.join(',')+'}';gap=mind;return v;}}
if(typeof JSON.stringify!=='function'){meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};JSON.stringify=function(value,replacer,space){var i;gap='';indent='';if(typeof space==='number'){for(i=0;i<space;i+=1){indent+=' ';}}else if(typeof space==='string'){indent=space;}
rep=replacer;if(replacer&&typeof replacer!=='function'&&(typeof replacer!=='object'||typeof replacer.length!=='number')){throw new Error('JSON.stringify');}
return str('',{'':value});};}}
());try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={"id":id};}catch(e){u=utag.sender[id];}
utag.globals=window.utag.globals||{};u.ev={"all":1};u.performance_timing_count=0;u.account=utag.cfg.utid.split("/")[0];u.request_increment=1;u.iab_v11_compliance=true;u.iab_v20_compliance=true;u.tc_string="";u.deepCopy=function(input){var key,copy;if(typeof input==="object"&&input!==null){if(utag.ut.typeOf(input)==="array"){copy=[];}else{copy={};}
for(key in input){if(typeof input[key]==="object"){copy[key]=u.deepCopy(input[key]);}else{copy[key]=input[key];}}}else{copy=input;}
return copy;}
u.enrichment_enabled={};u.get_account_profile=function(s){var p;if(u.visitor_service_override||u.tag_config_server.indexOf("tealiumiq.com")===-1){p=[u.tag_config_server.split("//")[1],u.account,u.profile]}else{p=s.substring(s.indexOf(u.server_domain)).split("/");}
return p;};function infixParameters(url,params){var updated_url,url_parts=url.split("?");if(params){if(url_parts[1]===undefined){updated_url=url+"?"+params;}else if(url_parts[1]===""){updated_url=url+params;}else{updated_url=url_parts[0]+"?"+params+"&"+url_parts[1];}}else{updated_url=url;}
return updated_url;}
u.is_in_sample_group=function(b){var group="100";if(u.tag_config_sampling===""||u.tag_config_sampling==="100"){return true;}
if(b["cp.utag_main_dc_group"]){group=b["cp.utag_main_dc_group"];}else{group=Math.floor(Math.random()*100)+1;utag.loader.SC("utag_main",{"dc_group":group});}
if(parseInt(group)<=parseInt(u.tag_config_sampling)){return true;}else{return false;}};u.get_performance_timing=function(b){var t,timing;var data={};function subtract(val1,val2){var difference=0;if(val1>val2){difference=val1-val2;}
return difference;}
if(typeof localStorage!="undefined"&&JSON.parse&&window.performance&&window.performance.timing){t=window.performance.timing;timing=localStorage.getItem("tealium_timing");if(timing!==null&&timing!=="{}"&&typeof b!=="undefined"&&u.performance_timing_count===0){utag.ut.merge(b,utag.ut.flatten({timing:JSON.parse(timing)}),1);}}else{return;}
u.performance_timing_count++;for(var k in t){if((k.indexOf("dom")===0||k.indexOf("load")===0)&&t[k]===0&&u.performance_timing_count<20){setTimeout(u.get_performance_timing,1000);}}
data["domain"]=location.hostname+"";data["pathname"]=location.pathname+"";data["query_string"]=(""+location.search).substring(1);data["timestamp"]=(new Date()).getTime();data["dns"]=subtract(t.domainLookupEnd,t.domainLookupStart);data["connect"]=subtract(t.connectEnd,t.connectStart);data["response"]=subtract(t.responseEnd,t.responseStart);data["dom_loading_to_interactive"]=subtract(t.domInteractive,t.domLoading);data["dom_interactive_to_complete"]=subtract(t.domComplete,t.domInteractive);data["load"]=subtract(t.loadEventEnd,t.loadEventStart);data["time_to_first_byte"]=subtract(t.responseStart,t.connectEnd);data["front_end"]=subtract(t.loadEventStart,t.responseEnd);data["fetch_to_response"]=subtract(t.responseStart,t.fetchStart);data["fetch_to_complete"]=subtract(t.domComplete,t.fetchStart);data["fetch_to_interactive"]=subtract(t.domInteractive,t.fetchStart);try{localStorage.setItem("tealium_timing",JSON.stringify(data));}catch(e){utag.DB(e);}};u.validateProtocol=function(address,force_ssl){if(/^https?:\/\//i.test(address)){if(force_ssl){if(/^http:\/\//i.test(address)){address=address.toLowerCase().replace("http","https");}}}else{if(/^\/\//.test(address)){if(force_ssl){address="https:"+address;}else{address=location.protocol+address;}
}else{if(force_ssl){address="https://"+address;}else{address=location.protocol+"//"+address;}}}
return address;}
Number.isNaN=Number.isNaN||function isNaN(input){return typeof input==='number'&&input!==input;}
u.map={"hsbc_stream_server_list":"server_list","hsbc_stream_server_domain":"server_domain","hsbc_stream_server_prefix":"server_prefix","hsbc_stream_tag_config_server":"tag_config_server","hsbc_stream_tag_config_sampling":"tag_config_sampling","hsbc_stream_tag_config_region":"tag_config_region","hsbc_stream_region":"region","hsbc_stream_profile":"profile","hsbc_stream_performance_timing_count":"performance_timing_count","hsbc_stream_data_enrichment":"data_enrichment","hsbc_stream_profile_specific_vid":"profile_specific_vid","hsbc_stream_enrichment_polling":"enrichment_polling","hsbc_stream_enrichment_polling_delay":"enrichment_polling_delay","hsbc_stream_d_center_override":"center"};u.extend=[function(a,b){try{if(1){b['hsbc_stream_servers_1']='//collect.tealiumiq.com/hsbc/wpb-stream-uk/2/i.gif';b['hsbc_stream_server_domain']='tealiumiq.com';b['hsbc_stream_server_prefix']='';b['hsbc_stream_tag_config_server']='';b['hsbc_stream_tag_config_sampling']='100';b['hsbc_stream_tag_config_region']='default';b['hsbc_stream_region']='Ireland';b['hsbc_stream_profile']='wpb-stream-uk';b['hsbc_stream_performance_timing_count']='0';b['hsbc_stream_data_enrichment']='frequent';b['hsbc_stream_profile_specific_vid']='0';b['hsbc_stream_enrichment_polling']='1';b['hsbc_stream_enrichment_polling_delay']='1';b['vendor_hsbc_audience_chunk']='1'}}catch(e){utag.DB(e);}}];u.send=function(a,b){var c,d,i;u.data={server_list:[],server_domain:"tealiumiq.com",server_prefix:"",tag_config_server:"",tag_config_sampling:"100",tag_config_region:"default",region:"",center:null,profile:null,performance_timing_count:0,data_enrichment:"",profile_specific_vid:0,enrichment_polling:1,enrichment_polling_delay:1000};if(u.ev[a]||typeof u.ev["all"]!=="undefined"){if(a==="remote_api"){utag.DB("Remote API event suppressed.");return;}
if((u.iab_v11_compliance===true||u.iab_v11_compliance==="true")&&typeof __cmp==="function"){__cmp("getVendorConsents",[522],function(consents,is_successful){var consented_to_tealium=consents.vendorConsents[522];var consented_to_purposes=consents.purposeConsents[1]&&consents.purposeConsents[2]&&consents.purposeConsents[3]&&consents.purposeConsents[5];if(consented_to_tealium&&consented_to_purposes){execute_send();}else{utag.DB("Detected that consent was not granted for Tealium and/or its listed purposes. Aborting Tealium Collect.");}});}else if(u.iab_v20_compliance===true||u.iab_v20_compliance==="true"){if(typeof __tcfapi==="function"){__tcfapi("getTCData",2,function(tcData,success){if(success){u.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.tc_string+="1";}else if(tcData.gdprApplies===false){u.tc_string+="0";}else{u.tc_string+=String(tcData.gdprApplies);}
u.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}else{var frame=window;var cmpFrame;var cmpCallbacks={};while(frame){try{if(frame.frames["__tcfapiLocator"]){cmpFrame=frame;break;}}catch(error){utag.DB(error);}
if(frame===window.top){break;}
frame=frame.parent;}
if(!cmpFrame){execute_send();}else{window.__tcfapi=function(cmd,version,callback,arg){var callId=String(Math.random());var msg={__tcfapiCall:{command:cmd,parameter:arg,version:version,callId:callId}};cmpCallbacks[callId]=callback;cmpFrame.postMessage(msg,"*");};window.tealiumiabPostMessageHandler=function(event){var json={};try{json=typeof event.data==="string"?JSON.parse(event.data):event.data;}catch(error){utag.DB(error);}
var payload=json.__tcfapiReturn;if(payload){if(typeof cmpCallbacks[payload.callId]==="function"){cmpCallbacks[payload.callId](payload.returnValue,payload.success);cmpCallbacks[payload.callId]=null;}}};window.addEventListener("message",tealiumiabPostMessageHandler,false);__tcfapi("getTCData",2,function(tcData,success){if(success){u.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.tc_string+="1";}else if(tcData.gdprApplies===false){u.tc_string+="0";}else{u.tc_string+=String(tcData.gdprApplies);}
u.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}}}else{execute_send();}
function execute_send(){u.make_enrichment_request=false;for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.get_performance_timing(b);//@HSBC CUSTOMIZE UDO MAPPINGSfor(d in u.data){if(u.data[d]!=""&&!isNaN(u.data[d])){u.data[d]=Number(u.data[d]);}}
try{b["hsbc_stream_server_list"]=[];function cleanString(str){return str.replace("\"","");}
function assignServers(b){var servers="hsbc_stream_servers_",str;for(items in b){if(TMS.util.hasOwn(b,items)&&items.toString().indexOf(servers)>-1){b["hsbc_stream_server_list"].push(cleanString(b[items]));}}}
assignServers(b)}catch(e){utag.DB(e)}
u.server_list=u.data.server_list||u.tag_config_server.split("|");u.server_list=b["hsbc_stream_server_list"]||u.server_list;u.server_domain=u.data.server_domain;u.server_prefix=u.data.server_prefix||"";u.tag_config_server=u.data.tag_config_server||"";u.tag_config_sampling=u.data.tag_config_sampling||""||"100";if(utag.cfg.utagdb){u.tag_config_sampling="100";}
if(!u.is_in_sample_group(b)){return false;}
u.tag_config_region=u.data.tag_config_region||""||"default";u.data.region=(u.data.region&&u.data.region.toUpperCase());var dataloc=u.data.center||{"SYDNEY":"ap-southeast-2","US EAST":"us-east-1","TOKYO":"ap-northeast-1","HK":"ap-east-1","IRELAND":"eu-west-1","GERMANY":"eu-central-1","GLOBAL":null};if(dataloc[u.data.region]){u.region=dataloc[u.data.region];}else{b["cp.utag_main_dc_region"]=null
u.region=null;}
u.data_source=u.data.data_source||"";if(u.data_source){b.tealium_datasource=u.data_source;}
u.profile=u.data.profile||""||utag.cfg.utid.split("/")[1];u.visitor_service_override=u.data.visitor_service_override||"";var q=u.tag_config_server.indexOf("?");if(q>0&&(q+1)==u.tag_config_server.length){u.tag_config_server=u.tag_config_server.replace("?","");}
if(u.tag_config_server.indexOf("-collect."+u.server_domain)>1){u.server_prefix=u.tag_config_server.split("collect."+u.server_domain)[0];if(u.tag_config_server.indexOf("/i.gif")<0){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_server===""){if(u.tag_config_region==="default"){u.tag_config_server="https://"+[u.server_prefix+"collect."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}else{u.tag_config_server="https://"+[u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain,u.account,u.profile,"2","i.gif"].join("/");}}
if(u.tag_config_server.indexOf("-collect-")>-1){u.server_prefix=u.tag_config_server.split("collect-")[0];}
if(u.tag_config_region!=="default"&&u.tag_config_server.indexOf(u.server_prefix+"collect."+u.server_domain)>0){u.tag_config_server=u.tag_config_server.replace(u.server_prefix+"collect."+u.server_domain,u.server_prefix+"collect-"+u.tag_config_region+"."+u.server_domain);u.region=u.tag_config_region;}
u.data_enrichment=u.data.data_enrichment||"";u.profile_specific_vid=u.data.profile_specific_vid||0;u.enrichment_polling=u.data.enrichment_polling||1;u.enrichment_polling_delay=u.data.enrichment_polling_delay||500;u.do_enrichment=function(){};for(i=0;i<u.server_list.length;i++){if(u.server_list[i].toLowerCase().indexOf("http")===-1){u.server_list[i]=u.validateProtocol(u.server_list[i],true);}
if(b["cp.utag_main_dc_region"]||u.region){u.region=u.region||b["cp.utag_main_dc_region"];u.server_list[i]=u.server_list[i].replace("datacloud.","datacloud-"+u.region+".");u.server_list[i]=u.server_list[i].replace("collect.","collect-"+u.region+".");}
if(u.enrichment_enabled[i]!==false){u.enrichment_enabled[u.server_list[i]]=true;}}
//@HSBC END UDO MAPPING CUSTOMIZATIONif(u.server_list.length>1){u.profile_specific_vid=1;}
//@HSBC CUSTOMIZATIONif(utag.datacloud){u.data=utag.datacloud;}
u.data["loader.cfg"]={};for(d in utag.loader.GV(utag.loader.cfg)){if(utag.loader.cfg[d].load&&utag.loader.cfg[d].send){utag.loader.cfg[d].executed=1;}else{utag.loader.cfg[d].executed=0;}
u.data["loader.cfg"][d]=utag.loader.GV(utag.loader.cfg[d]);}
//@HSBC END CUSTOMIZATION(function(a,b){var loaded=false;if(!loaded){function tec(b,storage,profile){utag.hsbc=utag.hsbc||{};utag.hsbc.extensions=utag.hsbc.extensions||{};utag.hsbc.extensions.totalCount=0;utag.hsbc.extensions.sizeBuckets={s:0,m:0,l:0};utag.hsbc.extensions.totalSize=0;utag.hsbc.extensions.count=function(extendDetails){var size=extendDetails.length;var bucket;if(size<500){bucket='s'}else if(size<1000){bucket='m'}else{bucket='l'}
utag.hsbc.extensions.sizeBuckets[bucket]++;utag.hsbc.extensions.totalCount++;utag.hsbc.extensions.totalSize+=size;}
var i,key;var extendLength=utag.handler.extend.length;for(i=0;i<extendLength;i++){utag.hsbc.extensions.count(utag.handler.extend[i].toString());}
for(key in utag.sender){if(utag.sender[key].extend){extendLength=utag.sender[key].extend.length;for(i=0;i<extendLength;i++){utag.hsbc.extensions.count(utag.sender[key].extend[i].toString());}}}
storageData=localStorage['tealiumExtCount']+'|'+profile;var ext=utag.hsbc.extensions.sizeBuckets;localStorage['tealiumExtCount']=storageData;b['tealium_extension_count']="s:"+ext.s+"|m:"+ext.m+"|l:"+ext.l+"|total:"+utag.hsbc.extensions.totalCount+"|totalSize:"+Math.round(utag.hsbc.extensions.totalSize/1000)+"kb";}
function Keywords(callEvent,engine,matched,keyw,adId){this.callEvent=callEvent||false,this.engine=engine;this.matched=matched;this.keyw=keyw;this.adId=adId;}
Keywords.prototype={constructor:Keywords,process:(function(b){if(b['qp.SearchEngine']&&/\w{0,15}/.test(b['qp.SearchEngine'])){var engine=encodeURIComponent(b['qp.SearchEngine']);}
if(b['qp.MatchType']&&/\w{0,10}/.test(b['qp.MatchType'])){var matched=encodeURIComponent(b['qp.MatchType']);}
if(b['qp.AdID']&&/\w\d/.test(b['qp.AdID'])){var adId=encodeURIComponent(b['qp.AdID']);}
if(b['qp.Keyword']&&/(?:\w|\d|[\u3000\u3400-\u4DBF\u4E00-\u9FFF])/.test(b['qp.Keyword'])){var keyw=b['qp.Keyword'].replace(/\+/g," ");var callEvent=true;}
Keywords.call(Keywords,callEvent,engine,matched,keyw,adId);})(b),run:function(){var that=this.constructor;return{'paid_search_term':(that.engine+"|"+that.matched+"|"+that.adId+"|"+that.keyw).toLowerCase(),}}};function Rebuild(aa,bb){if(!!bb.paid_search_term){for(var ob in bb){if(bb.hasOwnProperty(ob)){aa[ob]=bb[ob];}}
return aa;}}
var scroll={dom:document,deltaDown:0,deltaUp:0,startPos:0,getScrollTop:function(){return Math.max(window.pageYOffset,document.documentElement.scrollTop,document.body.scrollTop);},getHeight:function(){return(this.dom.compatMode=="BackCompat")?this.dom.body.clientHeight:this.dom.documentElement.clientHeight;},maxPos:function(){return(Math.max(this.dom.documentElement.scrollHeight,this.getHeight())-Math.min(this.getHeight(),window.innerHeight))},pixel:function(){return this.deltaDown+this.deltaUp},percent:function(){var v=Math.round(this.pixel()/this.maxPos()*100,0);v=v>=100?100:(v<=0?0:v);return v;},pos:function(){var pos=this.getScrollTop();return pos<=0?0:pos;},delta:function(){return(this.pos()-this.startPos);},hasScrolled:function(){if(this.delta()>0&&this.deltaDown<this.delta()){this.deltaDown=this.delta();this.setScrollDepth();}
if(this.delta()<0&&this.deltaUp<-this.delta()){this.deltaUp=-this.delta();this.setScrollDepth();}},init:function(){localStorage["HSBCscrollDepthPerc"]=(window.location.hostname+'|0');utag_data['cp.HSBCscrollDepthPerc']=(window.location.hostname+'|0');this.startPos=this.getScrollTop();window.Evnt.addE(document,'scroll',this.hasScrolled.bind(this));},setScrollDepth:function(){localStorage["HSBCscrollDepthPerc"]=(window.location.hostname+'|'+this.percent());utag_data['cp.HSBCscrollDepthPerc']=(window.location.hostname+'|'+this.percent());if(this.percent()<=100){window.Evnt.removeE(document,'scroll',this.hasScrolled);}}};loaded=true;}
var excludedUDOs=["promotion_content_array","hsbc_audience_id","hsbc_audience_name","_cprod","_cprodname","_cbrand","_ccat","_ccat2","_cquan","_cprice","_csku","_cpdisc","meta.description","meta.twitter:description","meta.og:description","meta.app-itunes","tealium_lib_name_version","hsbc_stream_server_list","cp._cs_cvars","cp.insights_hub_uuid","cp.userAccessToken","consent_categories"];!function(a,b,func){window.TMS.debug=window.TMS.debug||[];b['datalayer_issue']='';var i,len;for(i=0,len=func.length;i<len;i++){try{if(func[i].rule){func[i].func.call(func,a,b);}}catch(e){TMS.debug.push(e);}}}
(a,b,[{rule:b["vendor_hsbc_audience_chunk"],func:function(a,b){var hsbc_audience_name=[],hsbc_audience_id=[],storage=localStorage.getItem(['tealium_va']),aud=JSON.parse(storage)['audiences'];var audience_name_buckets=[""],audience_id_buckets=[""],increment_name=0,increment_id=0,property;for(property in aud){if({}.hasOwnProperty.call(aud,property)&&TMS.util.check.isDefined(aud[property])){hsbc_audience_name.push(aud[property]);hsbc_audience_id.push(property);}}
b["hsbc_audience_name"]=utag_data["hsbc_audience_name"]=hsbc_audience_name;b["hsbc_audience_id"]=utag_data["hsbc_audience_id"]=hsbc_audience_id;}},{rule:!b["vendor_hsbc_audience_chunk"],func:function(a,b){var hsbc_audience=hsbc_audience_name=hsbc_audience_id="",storage=localStorage.getItem(['tealium_va']),aud=JSON.parse(storage)['audiences'],property;for(property in aud){if({}.hasOwnProperty.call(aud,property)&&TMS.util.check.isDefined(aud[property])){hsbc_audience+=aud[property]+", "}}
hsbc_audience=hsbc_audience.replace(/,\s*$/,"");b['hsbc_audience']=utag_data['hsbc_audience']=hsbc_audience;}},{rule:(utag.gdpr&&(utag.gdpr.consent_prompt.isEnabled||utag.gdpr.getConsentState())),func:function(a,b){b["consent_categories"]=utag.gdpr.getSelectedCategories();b["consent_categories_stream"]=utag.gdpr.getSelectedCategories();b["policy"]="gdpr";}},{rule:true,func:function(a,b){for(var k in utag_data){if(TMS.util.hasOwn(utag_data,k)&&TMS.util.check.isDefined(utag_data[k])&&k.indexOf("location_")!=-1){b[k]=utag_data[k];}}
return b;}},{rule:true,func:function(){utag_data["adobe_analytics_currency_override"]?currency=utag_data["adobe_analytics_currency_override"]:"USD";}},{rule:true,func:function(a,b){if(TMS.util.check.isDefined(b['promotion_content'])){if(TMS.util.check.isArray(b['promotion_content'])){b['promotion_content_array']=b['promotion_content'];}else{b['promotion_content_array']=b['promotion_content'].split(",");}}}},{rule:b["vendor_hsbc_promotion_chunk"],func:function(a,b){var promotion_name="";var buckets=[""],increment=0;var property;for(property in b['promotion_content_array']){promotion_name=b['promotion_content_array'][property]+", "
if((buckets[increment].length+promotion_name.length)<1e3){buckets[increment]+=promotion_name;}else{increment++;buckets[increment]=promotion_name;}}
for(var i=0;i<buckets.length;i++){buckets[i]=buckets[i].replace(/,\s*$/,"");if(i>0){b['promotion_content_'+i]=utag_data['promotion_content_'+i]=buckets[i];}else{b['promotion_content']=utag_data['promotion_content']=buckets[i];}}}},{//@B.O.T Identificationrule:true,func:function(a,b){var user_agent=window.navigator.userAgent;var re=(typeof b["bot_id_rule"]!=="undefined")?new RegExp(b["bot_id_rule"],"i"):/bot|PTST|spider|crawler/i;b["is_robo"]=false;if(re.test(user_agent)){b["is_robo"]=true;}}},{rule:true,func:function(a,b){var Storage=localStorage["HSBCscrollDepthPerc"]||'';if(Storage!=''){var k=Storage.split('|');b['hsbcscrolldepth']=k[1];b['page_percent_viewed']=b['hsbcscrolldepth'];}}},{rule:(a==="view"),func:function(a,b){delete localStorage["HSBCscrollDepthPerc"];scroll.init();}},{rule:(b["site_category"]!="mobileapp"),func:function(a,b){b["page_tech"]=(utag.data.site_type==="single_page")?"single-page":"multi-page";b['timestamp']=Date.now();var tealiumEvnt=new CustomEvent("tealiumEvnt",{detail:a});window.window.dispatchEvent(tealiumEvnt);}},{rule:/pws/i.test(b['page_name']),func:function(a,b){var pii={env:{win_loc:window.location,},rgx:{email:/^.{2,30}(@|%40).{2,10}\.\w{2,5}$/},keyBL:['name','firstname','email','street','dob','postcode','zip','address','login'],test:function(val,test){var result=this.rgx[test].exec(val);if(result){val=val.replace(result[0],'xxxx'+test+'xxxx');}
return val;},encode:function(val){return encodeURIComponent(val)},getQSParamSet:function(){var loc_search_raw=this.env.win_loc.search,loc_search="",cap=32e3;if(typeof loc_search_raw=='undefined'||loc_search_raw==null){loc_search=""}else{var i,limit;loc_search_raw=String(loc_search_raw)
limit=(loc_search_raw.length<cap)?loc_search_raw.length:cap;for(i=0;i<limit;i++){loc_search+=loc_search_raw[i];}
loc_search=loc_search.substring(1)}
return loc_search;},qsKeyCheck:function(){var qsp=this.getQSParamSet().split('&'),qsi=(qsp.length-1),bli=(this.keyBL.length-1),x,keyVal;for(qsi;qsi>=0;qsi--){for(x=bli;x>-1;x--){keyVal=qsp[qsi].split('=');if(keyVal[0].indexOf(this.keyBL[x])>-1){keyVal[1]='xxxx';qsp[qsi]=this.encode(keyVal[0])+"="+this.encode(keyVal[1]);}}}
return qsp.join('&');},captureFullUrl:function(){var qs=this.qsKeyCheck(),testResult=this.test(qs,'email'),formatted=(typeof testResult!=="undefined"&&testResult!="")?"?"+testResult:testResult,full=(this.env.win_loc.hostname+this.env.win_loc.pathname);if(/xxxx/.test(formatted)){formatted='?xxxx-masked-xxxx';}
return(full+formatted);},utagCheckList:['site_country'],checkUtag:function(){var i=this.utagCheckList.length-1;for(i;i>=0;i--){utag=this.test(utag_data[this.utagCheckList[i]],'email');utag_data[this.utagCheckList[i]]=utag;}}};b['url_querystring']=pii.captureFullUrl();}},{rule:true,func:function(a,b){var cookie=utag_data['cp.tealiumExtCount']||'';var profile=utag_data.tealium_profile;if(a=="view"&&cookie.indexOf(profile)<0){tec(b,cookie,profile);}}},{rule:a==='view',func:function(a,b){var l=new Keywords(),c=Rebuild(b,l.run());b=c;return b;}},{rule:true,func:function(a,b){try{if((typeof b['site_category']=='undefined'&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['site_category']='web';}}catch(e){utag.DB(e)}
try{if(b['page_name'].toString().toLowerCase().indexOf('404'.toLowerCase())>-1||b['pageType']=='errorPage'){b['adobe_errorpage']='errorPage';try{b['page_name_en']="404:"+window.location.href;}catch(e){};try{b['page_name']="404:"+window.location.href;}catch(e){}}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='verification'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='logon'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['token_usage']=b['event_content'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='vam'.toLowerCase()&&typeof b['event_action']!='undefined'&&b['event_action']!=''&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['vam_event']=b['event_action'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='tool'.toLowerCase()&&b['event_subcategory'].toString().toLowerCase()=='interaction'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['tool_type']=b['event_action'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='lead'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='complete'.toLowerCase())||(b['event_category'].toString().toLowerCase()=='lead'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='captured'.toLowerCase())){b['lead_event']=b['event_action'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='click'.toLowerCase()&&typeof b['event_content']!='undefined'&&b['event_content']!='')){b['click_content']=b['event_content'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='transaction'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='start'.toLowerCase())||(b['event_category'].toString().toLowerCase()=='transaction'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase())){b['transaction_name']=b['transaction_id'];}}catch(e){utag.DB(e)}
try{if((typeof b['tool_name']!='undefined'&&b['tool_name']!=''&&b['event_category'].toString().toLowerCase()=='tool'.toLowerCase()&&b['event_subcategory'].toString().toLowerCase()=='interaction'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='link'.toLowerCase())){b['tool_event']='interaction';}}catch(e){utag.DB(e)}
try{if((typeof b['tool_name']!='undefined'&&b['tool_name']!=''&&b['event_category'].toString().toLowerCase()=='tool'.toLowerCase()&&b['event_subcategory'].toString().toLowerCase()=='complete'.toLowerCase()&&typeof b['event_action']!='undefined'&&b['event_action']!='')){b['tool_event']='completed';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='tool'.toLowerCase()&&b['event_subcategory'].toString().toLowerCase()=='search'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='complete'.toLowerCase())){b['search_category']='search';}}catch(e){utag.DB(e)}
try{if(b['search_results'].toString().toLowerCase()=='0'.toLowerCase()){b['search_action']='no_results';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='verification'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='registration'.toLowerCase())){b['registration_event']='completed';}}catch(e){utag.DB(e)}
try{if((b['product_event'].toString().toLowerCase()=='apst'.toLowerCase()&&typeof b['application_event']=='undefined'&&typeof b['event_category']=='undefined'&&typeof b['event_action']=='undefined'&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['application_event']='started';b['event_category']='application';b['event_action']='start'}}catch(e){utag.DB(e)}
try{if((b['product_event'].toString().toLowerCase()=='apsu'.toLowerCase()&&typeof b['application_event']=='undefined'&&typeof b['event_category']=='undefined'&&typeof b['event_action']=='undefined'&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['application_event']='submitted';b['event_category']='application';b['event_action']='submit'}}catch(e){utag.DB(e)}
try{if((b['product_event'].toString().toLowerCase()=='trco'.toLowerCase()&&typeof b['transaction_event']=='undefined'&&typeof b['event_category']=='undefined'&&typeof b['event_action']=='undefined'&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['transaction_event']='completed';b['event_category']='transaction';b['event_action']='submit'}}catch(e){utag.DB(e)}
try{if((typeof b['event_category']=='undefined'&&b['event_action'].toString().toLowerCase()=='registration'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())||(typeof b['event_category']=='undefined'&&b['event_action'].toString().toLowerCase()=='logon'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())||(typeof b['event_category']=='undefined'&&b['event_action'].toString().toLowerCase()=='logins'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['event_category']='verification'}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='start'.toLowerCase())){b['application_event']='started';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase())){b['application_event']='submitted';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase()&&b['event_content'].toString().toLowerCase()=='accepted'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())){b['application_event']='accepted';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase()&&b['event_content'].toString().toLowerCase()=='declined'.toLowerCase())){b['application_event']='declined';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase()&&b['event_content'].toString().toLowerCase()=='referred'.toLowerCase())){b['application_event']='referred';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='application'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='submit'.toLowerCase()&&b['event_content'].toString().toLowerCase()=='completed'.toLowerCase())){b['application_event']='completed';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='transaction'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='error'.toLowerCase())){b['transaction_event']='error';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='transaction'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='complete'.toLowerCase())){b['transaction_event']='completed';}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='verification'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='logon'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())||(b['event_category'].toString().toLowerCase()=='verification'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='logins'.toLowerCase()&&b['ut.event'].toString().toLowerCase()=='view'.toLowerCase())||(b['event_category'].toString().toLowerCase()=='verification'.toLowerCase()&&b['event_subcategory'].toString().toLowerCase()=='logon'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='complete'.toLowerCase())){b['login_event']='logged_in';}}catch(e){utag.DB(e)}
try{if((b['promotion_category'].toString().toLowerCase()=='internal_promotion'.toLowerCase()&&b['promotion_action'].toString().toLowerCase()=='display'.toLowerCase())){b['promotion_event']=b['promotion_action'];}}catch(e){utag.DB(e)}
try{if((b['event_category'].toString().toLowerCase()=='lead'.toLowerCase()&&b['event_action'].toString().toLowerCase()=='complete'.toLowerCase())){b['adobe_analytics_multifactorevent']='ev26';}}catch(e){utag.DB(e)}
try{if(b['event_category'].toString().toLowerCase()=='social'.toLowerCase()){b['adobe_analytics_evar45']=b['event_action'];}}catch(e){utag.DB(e)}
(function(a,b,c,d){c=['link_name'];for(d=0;d<c.length;d++){try{b[c[d]]=(b[c[d]]instanceof Array||b[c[d]]instanceof Object)?b[c[d]]:b[c[d]].toString().toLowerCase();}catch(e){}}
return b;}
())
try{if(b['page_type']=='product'){b['adobe_page_event']='prodView';}}catch(e){utag.DB(e)}
try{if((typeof b['vam_id']!='undefined'&&/accept|decline|like|dislike|abandon/.test(b['vam_action']))){b['pid_content']=b['vam_id'];}}catch(e){utag.DB(e)}
try{if((typeof b['site_section']=='undefined'&&typeof b['page_category']!='undefined')){b['site_section']=b['page_category'];}}catch(e){utag.DB(e)}
try{if((typeof b['amount']=='undefined'&&typeof b['total_amount_payable']!='undefined')){b['amount']=b['total_amount_payable'];}}catch(e){utag.DB(e)}
try{if(typeof b['link_name']=='undefined'){if((typeof b['event_category']!='undefined'&&typeof b['event_action']!='undefined'&&/tab|click|accordion|popup|onsite|download|dropdown|radio|toggle|button|advance expander/.test(b['event_action'])&&typeof b['event_content']!='undefined')){try{b['adobe_analytics_linkname']=b.event_category+"|"+b.event_action+"|"+b.event_content;b['link_name']=b.event_category+"|"+b.event_action+"|"+b.event_content;}catch(e){}}}}catch(e){utag.DB(e)}
try{if((b['event_category']=='tool'&&b['event_subcategory']=='search'&&b['event_action']=='result-click')){b['search_action']='result-click';}}catch(e){utag.DB(e)}
try{if(typeof b['ut.env']!='undefined'&&typeof b['ut.profile']!='undefined'){b['ut.profile']=b['ut.profile'];}}catch(e){utag.DB(e)}
try{if(b['account_type']&&b['account_country']&&b['account_currency']&&b['account_status']){b['account_combi']=b['account_type']+'|'+b['account_country']+'|'+b['account_currency']+'|'+b['account_status'];}
if(b['transfer_after_days']){var transfer=b['transfer_after_days'];}else if(b['transfer_date']){var transfer=b['transfer_date'];}
if(b['transfer_immediacy']&&transfer&&b['sender_currency']&&b['recipient_currency']&&b['transfer_method']){b['transfer_combi']=b['transfer_immediacy']+'|'+transfer+'|'+b['sender_currency']+'|'+b['recipient_currency']+'|'+b['transfer_method'];}}catch(e){utag.DB(e)}}},{rule:true,func:function(a,b){var property,keys=[],key,data,tealium_lib_name_version=[],key_data,utversion,pub_time,publish_time,pub_date,publish_date,publish_timestamp,utagjs_version,tealium_env_values;for(property in utag_data){if(utag_data.hasOwnProperty(property)){if(/tmsLibVer_/.test(property)&&!(/tmsLibVer_celebrus/.test(property))){keys.push(property);}else if(/vendor_celebrus_version_trigger/.test(property)){keys.push(property);}}}
keys=keys.sort();for(var i=0,klen=keys.length;i<klen;i++){key=keys[i];data=utag_data[key];if(data!==undefined&&data!==""&&typeof data!=="function"){if(key.indexOf('tmsLibVer_')>-1){key=key.split('tmsLibVer_')[1];}else if(key.indexOf('_version_trigger')>-1){key=key.split('_')[1];}
key_data=key+":"+data;tealium_lib_name_version.push(key_data);}}
var tealium_lib_name_version_filtred=[];if(tealium_lib_name_version.join().indexOf('promotiontracking_combined:')>-1){for(var i=0;i<tealium_lib_name_version.length;i++){if(tealium_lib_name_version[i].indexOf('promotiontracking')==-1||tealium_lib_name_version[i].indexOf('promotiontracking_combined:')>-1){tealium_lib_name_version_filtred.push(tealium_lib_name_version[i])}}
tealium_lib_name_version=tealium_lib_name_version_filtred;}
b.tealium_lib_name_version=tealium_lib_name_version;utversion=b["ut.version"]
pub_time=utversion.substr(-4);publish_time=[pub_time.slice(0,2),pub_time.slice(2,4)].join(":")+"GMT";pub_date=(utversion.slice(0,-4).substr(-8));publish_date=[pub_date.slice(0,4),pub_date.slice(4,6),pub_date.slice(6,8)].join("-");publish_timestamp=publish_date+" "+publish_time;utagjs_version=utversion.slice(0,-13).replace("ut","utag:");tealium_env_values=utagjs_version+":"+publish_timestamp;tealium_lib_name_version.unshift(tealium_env_values);b["tealium_env_values"]=tealium_lib_name_version.join("|");}},{rule:true,func:function(a,b){b['vendor_adobeanalytics_appid']=b.app_name+" "+b.app_version;}},{rule:(b.tagdevicetype==="mobile"),func:function(a,b){b['site_category']='mobileapp';}},{rule:b['ut.env']=='prod',func:function(a,b){b['site_domain_type']='prod'}},{rule:true,func:function(a,b){b.tealium_event_uuid=(function(){var str='xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx';return str.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=(c=='x')?r:(r&0x3|0x8);return v.toString(16);});})();}},{rule:true,func:function(a,b){b.adobe_rsid_copy=b.adobe_rsid;if(utag.data["ut.env"]!=="prod"){if(utag.data['ut.profile'].indexOf('hangseng')>-1){b.adobe_rsid='hsbc-hasedev-1';b.adobe_rsid_copy='hsbc-hasedev-1';}else{b.adobe_rsid='hsbc-rbwm-global-qa-1';b.adobe_rsid_copy='hsbc-rbwm-global-qa-1';}}}},{rule:true,func:function(a,b){var visitor=(window.s&&window.s.visitor);var orgid=b['adobe_analytics_orgid']||"AE9446FC57CECBEE7F000101";b['adobe_mcvid']=(b['adobe_mcvid']||(visitor&&visitor['_fields']&&visitor['_fields'].MCMID)||(/(?:\|MCMID\|(\d*)\|)/.exec(utag.data["cp.AMCV_"+orgid+"%40AdobeOrg"])[1])||(visitor&&visitor.getMarketingCloudVisitorID&&visitor.getMarketingCloudVisitorID()));}},{rule:b.tagdevicetype!="mobile",func:function(a,b){if(a=="view"&&utag.data.site_type=="single_page"){var requestStart=window.performance&&window.performance.timing&&window.performance.timing.requestStart||false;window.startTime=window.startTime||requestStart;if(window.startTime){b['page_load_time']=((new Date().getTime()-window.startTime)/1000).toFixed(3);}
window.addEventListener('click',function(){window.startTime=new Date().getTime();});}}},{rule:(b['page_url'].indexOf(b['dom.domain'])==-1),func:function(a,b){b['page_url']=b['dom.domain']+b['page_url'];}},{rule:true,func:function(a,b){b['link_name']=b['link_name'].toLowerCase();}},{rule:(a==='view'),func:function(a,b){if(b['cp.utag_main__prevpage']){b['previous_page_name']=b['cp.utag_main__prevpage'];}
if(b['page_name']){utag.loader.SC('utag_main',{'_prevpage':b['page_name']+';exp-session'});}}},{rule:true,func:function(a,b){function getTime(now){var day=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],hour=now.getHours(),min=now.getMinutes(),ampm=hour>=12?'PM':'AM';hour=hour%12;hour=hour?hour:12;min=min<10?'0'+min:min;return(hour+':'+min+' '+ampm+'|'+day[now.getDay()]);}
b.time_parting=getTime(new Date());}},{rule:(typeof b['qp.cid']!="undefined"),func:function(a,b){b.qp_cid=b['qp.cid'];}},{rule:(typeof b['qp.eid']!="undefined"),func:function(a,b){b.qp_eid=b['qp.eid'];}},{rule:document.getElementById("customer_id"),func:function(a,b){b.celebrus_customer_id=document.getElementById("customer_id").innerText;}},{rule:true,func:function(a,b){var win=window;if(TMS.util.check.isDefined(localStorage["cpi.tracking.id"])){b.customer_id=localStorage["cpi.tracking.id"];}else if(TMS.util.toObject("window.global_app_var.userId")){b.customer_id=win.global_app_var.userId;}else if(TMS.util.toObject("window.utag.data.customer_id")){b.customer_id=win.utag.data["customer_id"];}else{}}},{rule:true,func:function(a,b){b["height"]=window.innerHeight||document.body.clientHeight;b["width"]=window.innerWidth||document.body.clientWidth;b["screen_height"]=screen&&screen.height;b["screen_width"]=screen&&screen.width;b["timezone_offset"]=new Date().getTimezoneOffset();}},{rule:true,func:function(a,b){var numeric_udo_list=["app_memory_usage","amount"];var prop,inc;for(inc=0;inc<numeric_udo_list.length;inc++){for(prop in b){if(b.hasOwnProperty(prop)&&TMS.util.check.isString(b[prop])&&numeric_udo_list[inc]===prop){b[prop]=b[prop].replace(/(?:(?!\.)[\D])+/g,"");b[prop]=Number(b[prop])}}}}},{rule:true,func:function(a,b){var prop;for(prop in b){if(b.hasOwnProperty(prop)&&TMS.util.check.isString(b[prop])&&(b[prop].indexOf('"')>-1)&&(b[prop].lastIndexOf('}')===-1)&&(b[prop].indexOf('{')===-1)){b[prop]=b[prop].replace(/"/g,"");if(excludedUDOs.indexOf(prop)===-1){b['datalayer_issue']+='001:'+prop+'|';}}}}},{rule:true,func:function(a,b){var prop;for(prop in b){if(b.hasOwnProperty(prop)){if(b[prop][0]===" "||b[prop][b[prop].length-1]===" "){b[prop]=b[prop].trim();if(excludedUDOs.indexOf(prop)===-1){b['datalayer_issue']+='002:'+prop+'|';}}}}}},{rule:true,func:function(a,b){var prop;for(prop in b){if(b.hasOwnProperty(prop)&&/[\t\n\r]/g.test(b[prop])){b[prop]=b[prop].replace(/[\t\n\r]/g,' ');if(excludedUDOs.indexOf(prop)===-1){b['datalayer_issue']+='005:'+prop+'|';}}}}},{rule:true,func:function(a,b){var prop;for(prop in b){if(b.hasOwnProperty(prop)&&Array.isArray(b[prop])&&prop!=="promotion_content_array"&&prop!=="consent_categories"&&prop!=="hsbc_audience_id"&&prop!=="hsbc_audience_name"){b[prop]=b[prop].join("__");if(excludedUDOs.indexOf(prop)===-1){b['datalayer_issue']+='003:'+prop+'|';}}}}},{rule:true,func:function(a,b){var StringValue,prop;for(prop in b){if(b.hasOwnProperty(prop)){StringValue=String(b[prop]);if(StringValue.lastIndexOf("}")!=-1||StringValue.indexOf("{")!=-1||StringValue.lastIndexOf("]")!=-1||StringValue.indexOf("[")!=-1){var str={entity:{"'":'','"':'','[':'',']':'','{':'','}':''},stringify:function(chars){var self=this;return chars.replace(/["'\[\]{}]/g,function(c){return self.entity[c];});}};if(window.TMS.util.check.isString(b[prop])||window.TMS.util.check.isNum(b[prop])){b[prop]=str.stringify(String(b[prop]));}
if(excludedUDOs.indexOf(prop)===-1){b['datalayer_issue']+='004:'+prop+'|';}}}}}},{rule:(b.hasOwnProperty("adobe_analytics_linkname")),func:function(a,b){b["event_action"]="custom link";b["event_content"]=b["adobe_analytics_linkname"];}},{rule:true,func:function(a,b){var prop;for(prop in b){if(b.hasOwnProperty(prop)&&(typeof b[prop]==='undefined'||b[prop]===""||b[prop].toString().indexOf('undefined')>=0)){delete b[prop];}}}}])}
(a,b))
u.data.data=b;for(d in u.data.data){if((d+'').indexOf("qp.")===0){u.data.data[d]=encodeURIComponent(u.data.data[d]);}else if((d+'').indexOf("va.")===0){delete u.data.data[d];}}
if(!b["cp.utag_main_dc_event"]){b["cp.utag_main_dc_visit"]=(1+(b["cp.utag_main_dc_visit"]?parseInt(b["cp.utag_main_dc_visit"]):0))+"";}
b["cp.utag_main_dc_event"]=(1+(b["cp.utag_main_dc_event"]?parseInt(b["cp.utag_main_dc_event"]):0))+"";utag.loader.SC("utag_main",{"dc_visit":b["cp.utag_main_dc_visit"],"dc_event":b["cp.utag_main_dc_event"]+";exp-session"});utag.data["cp.utag_main_dc_visit"]=b["cp.utag_main_dc_visit"];utag.data["cp.utag_main_dc_event"]=b["cp.utag_main_dc_event"];var dt=new Date();u.data.browser={};try{u.data.browser["height"]=window.innerHeight||document.body.clientHeight;u.data.browser["width"]=window.innerWidth||document.body.clientWidth;u.data.browser["screen_height"]=screen.height;u.data.browser["screen_width"]=screen.width;u.data.browser["timezone_offset"]=dt.getTimezoneOffset();}catch(e){utag.DB(e);}
u.data["event"]=a+'';u.data["post_time"]=dt.getTime();if(u.data_enrichment==="frequent"||u.data_enrichment==="infrequent"){u.visit_num=b["cp.utag_main_dc_visit"];if(parseInt(u.visit_num)>1&&b["cp.utag_main_dc_event"]==="1"){u.enrichment_polling=2;}
try{u.va_update=parseInt(localStorage.getItem("tealium_va_update")||0);}catch(e){utag.DB(e);}
u.visitor_id=u.visitor_id||b.tealium_visitor_id||b["cp.utag_main_v_id"];if(u.data_enrichment==="frequent"||(u.data_enrichment==="infrequent"&&parseInt(u.visit_num)>1&&parseInt(b["cp.utag_main_dc_event"])<=5&&u.visit_num!==u.va_update)){u.make_enrichment_request=true;}
u.visitor_service_request=function(t,server){var s,p=u.get_account_profile(server);if(u.visitor_service_override){s=u.validateProtocol(u.visitor_service_override,true);}else{s=u.validateProtocol(u.server_prefix,true)+"visitor-service"+(u.region?"-"+u.region:"").replace(/[^-A-Za-z0-9+_.]/g,"")+"."+u.server_domain;}
(function(p){var prefix="tealium_va";var key="_"+p[1]+"_"+p[2];utag.ut["writeva"+p[2]]=function(o){utag.DB("Visitor Attributes: "+prefix+key);utag.DB(o);var str=JSON.stringify(o);if(str!=="{}"&&str!==""){try{localStorage.setItem("tealium_va_update",utag.data["cp.utag_main_dc_visit"]);localStorage.setItem(prefix,str);localStorage.setItem(prefix+key,str);}catch(e){utag.DB(e);}
if(typeof tealium_enrichment==="function"){tealium_enrichment(o,prefix+key);}}};}
(p.slice(0)));var vid=u.visitor_id;if(u.profile_specific_vid===1){vid+=p[2];}
utag.ut.loader({//@HSBC END CUSTOMIZATION (USE u.id instead of macro)id:"tealium_visitor_service_"+u.id+p[2]+"_"+u.request_increment++,src:s+"/"+p[1]+"/"+p[2]+"/"+vid.replace(/\?callback=.*/g,"")+"?callback=utag.ut%5B%22writeva"+encodeURIComponent(p[2].replace(/alert(.*?)/g,""))+"%22%5D&rnd="+encodeURIComponent(parseInt(t.toString().replace(/alert(.*?)/g,"")))});};u.do_enrichment=function(server,enrichment_polling,enrichment_polling_delay){if(typeof utag.ut.loader!="undefined"){for(i=0;i<enrichment_polling;i++){setTimeout(function(){u.visitor_service_request((new Date).getTime(),server);},i*enrichment_polling_delay+1);}}};}
var json_string,regExpReplace=new RegExp(u.visitor_id,"g");if(b.tealium_random&&typeof utag.globals[b.tealium_random]==="object"){for(var downstream_param in utag.globals[b.tealium_random]){u.data.data[downstream_param]=u.deepCopy(utag.globals[b.tealium_random][downstream_param]);}}
if(window.FormData){function postData(server_index,enrichment_polling,enrichment_polling_delay){if(server_index+1>u.server_list.length){return;}
var xhr=new XMLHttpRequest();var server=u.validateProtocol(u.server_list[server_index],true);var formData=new FormData();xhr.addEventListener("readystatechange",function(){if(xhr.readyState===3){try{u.region=xhr.getResponseHeader("X-Region")||u.region||"";}catch(res_error){utag.DB(res_error);u.region=u.region||"";}
if(u.region)
utag.loader.SC("utag_main",{"dc_region":u.region+";exp-session"});utag.DB("dc_region:"+u.region);}else if(xhr.readyState===4){postData(server_index+1,enrichment_polling,enrichment_polling_delay);if(u.make_enrichment_request&&u.enrichment_enabled[server]){u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);}}});if(u.server_list[server_index].toLowerCase().indexOf("http")!==0){u.server_list[server_index]=u.validateProtocol(u.server_list[server_index],true);}
u.server_list[server_index]=infixParameters(u.server_list[server_index],u.tc_string);xhr.open("post",u.server_list[server_index],true);xhr.withCredentials=true;json_string=JSON.stringify(u.data);if(u.profile_specific_vid===1&&u.visitor_id){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
formData.append("data",json_string);xhr.send(formData);}
postData(0,u.enrichment_polling,u.enrichment_polling_delay);}else{for(i=0;i<u.server_list.length;i++){(function(i,enrichment_polling,enrichment_polling_delay){var server=u.server_list[i];setTimeout(function(){json_string=JSON.stringify(u.data);if(u.profile_specific_vid==1&&u.visitor_id){json_string=json_string.replace(regExpReplace,u.visitor_id+u.get_account_profile(server)[2]);}
var img=new Image();img.src=server+"?"+(u.tc_string?u.tc_string+"&":"")+"data="+encodeURIComponent(json_string);if(u.make_enrichment_request&&u.enrichment_enabled[server]){u.do_enrichment(server,enrichment_polling,enrichment_polling_delay);}},i*700);}
(i,u.enrichment_polling,u.enrichment_polling_delay));}}}}};try{utag.o[loader].loader.LOAD(id);}catch(e){utag.loader.LOAD(id);}})("3676","hsbc.uk-rbwm")
}catch(e){utag.DB(e);}
