//tealium universal tag - utag.3727 ut4.0.202210271833, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;u.qsp_delim="&";if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"cp.utag_main_sskey":"sskey","product_id":"ex1","product_subcategory":"ex1","funnel_step_name":"ex2","application_status":"ex2","application_event":"ex2","vendor_optimise_channel":"vendor_optimise_channel","application_id":"appid","vendor_optimise_media_pixel_config":"url_params"};u.extend=[function(a,b){try{if(1){try{var om=utag.data["vend_om"];if(om){b['vendor_optimise_media_pixel_config']=om;}}catch(e){}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;if((typeof b['cp.utag_main_cid']=='undefined')||(typeof b['qp.cid']!='undefined')){utag.loader.SC('utag_main',{'cid':b['qp.cid']+';exp-30d'});b['cp.utag_main_cid']=b['qp.cid'];}
if(b['cp.utag_main_cid']&&b['cp.utag_main_cid'].toString().indexOf('A0')>-1){b['vendor_optimise_channel']='Optimise';}
else{b['vendor_optimise_channel']='non-optimise';}
utag.data['vendor_optimise_channel']=b['vendor_optimise_channel'];u.data={"base_url":'https://track.omguk.com/e/si/?Channel='+b["vendor_optimise_channel"]+'&'
};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};var params=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];params[e[f]]=b[d];}}}
if(!u.initialized){var paramsArray=Object.keys(params).map(function(key){return[String(key)+"="+params[key]];});var queryStrParams=paramsArray.join("&");queryStrParams=queryStrParams.replace("url_params=","");u.loader({"type":"img","src":u.data.base_url+queryStrParams});}
}};utag.o[loader].loader.LOAD(id);})("3727","hsbc.uk-rbwm");}catch(error){utag.DB(error);}
