//tealium universal tag - utag.3718 ut4.0.202210271833, Copyright 2022 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;u.ev={view:1,link:1};u.initialized=false;u.scriptrequested=false;u.map={"amazon_cookie_service_region":"region"};u.extend=[];u.regions={EU:'EU',NA:'NA'}
u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB("send:3718");utag.DB(data_layer);var a,b,c,d;a=utag_event;b=data_layer;u.data={qsp_delim:"&",kvp_delim:"=",eu_base_url:"https://aax-eu.amazon-adsystem.com/s/dcm?pid=76a94f42-342e-4e49-8d00-c8c2eddefafe",na_base_url:"https://s.amazon-adsystem.com/dcm?pid=f8ca2def-013b-4492-8956-75d0449638a4",base_url:"",tealium_visitor_id:"",region:"",iab_v20_compliance:true,tc_string:""};utag.DB("send:3718:EXTENSIONS");utag.DB(data_layer);for(var mapping_key in utag.loader.GV(u.map)){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==""){var destinations=u.map[mapping_key].split(",");for(var i=0;i<destinations.length;i++){u.data[destinations[i]]=data_layer[mapping_key];}}}
utag.DB("send:3718:MAPPINGS");utag.DB(u.data);if(u.data.iab_v20_compliance===true||u.data.iab_v20_compliance==="true"){if(typeof __tcfapi==="function"){__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.tc_string+="1";}else if(tcData.gdprApplies===false){u.data.tc_string+="0";}else{u.data.tc_string+=String(tcData.gdprApplies);}
u.data.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}else{var frame=window;var cmpFrame;var cmpCallbacks={};while(frame){try{if(frame.frames["__tcfapiLocator"]){cmpFrame=frame;break;}}catch(error){utag.DB(error);}
if(frame===window.top){break;}
frame=frame.parent;}
if(!cmpFrame){execute_send();}else{window.__tcfapi=function(cmd,version,callback,arg){var callId=String(Math.random());var msg={__tcfapiCall:{command:cmd,parameter:arg,version:version,callId:callId}};cmpCallbacks[callId]=callback;cmpFrame.postMessage(msg,"*");};window.tealiumiabPostMessageHandler=function(event){var json={};try{json=typeof event.data==="string"?JSON.parse(event.data):event.data;}catch(error){utag.DB(error);}
var payload=json.__tcfapiReturn;if(payload){if(typeof cmpCallbacks[payload.callId]==="function"){cmpCallbacks[payload.callId](payload.returnValue,payload.success);cmpCallbacks[payload.callId]=null;}}};window.addEventListener("message",tealiumiabPostMessageHandler,false);__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.tc_string+="1";}else if(tcData.gdprApplies===false){u.data.tc_string+="0";}else{u.data.tc_string+=String(tcData.gdprApplies);}
u.data.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}}}else{execute_send();}
function execute_send(){if(utag.loader.RC('utag_main')['amsyncran']){utag.DB("Same session detected; duplicate Amazon Cookie Matching call not sent.");return;}
if(u.data.region===u.regions.EU){u.data.base_url=u.data.eu_base_url;}else{u.data.base_url=u.data.na_base_url;}
u.data.tealium_visitor_id=u.data.tealium_visitor_id||data_layer.tealium_visitor_id||data_layer["ut.visitor_id"];u.data.base_url+=u.data.qsp_delim+"id"+u.data.kvp_delim+u.data.tealium_visitor_id;utag.loader.SC("utag_main",{"amsyncran":"1;exp-session"});if(u.data.base_url){var scriptUrl=u.data.base_url;var amazonCookieScrypt=document.createElement('script');amazonCookieScrypt.src=scriptUrl;document.getElementsByTagName('head')[0].appendChild(amazonCookieScrypt);}
utag.DB("send:3718:COMPLETE");}}};utag.o[loader].loader.LOAD(id);}("3718","hsbc.uk-rbwm"));}catch(error){utag.DB(error);}
