var loadGoogleMaps=function(){var a=!1;return function(b){var c=this;if(a)"function"==typeof b&&b.call(c);else{var d=SitePreferences.GoogleMapsUrl,f=SitePreferences.GoogleMapsApiKey;if(d&&f){var e=document.createElement("script");e.type="text/javascript";e.src=d+"key\x3d"+f;e.onload=function(){"function"==typeof b&&b.call(c)};document.body.appendChild(e);a=!0}}}}();
function getCookie(a){if(!("string"==typeof a||a instanceof String))return"";for(var b=a+"\x3d",c=decodeURIComponent(document.cookie).split(";"),d=0;d<c.length;d++){for(a=c[d];" "==a.charAt(0);)a=a.substring(1);if(0==a.indexOf(b))return a.substring(b.length,a.length)}return""}function appendParamToURL(a,b,c){return-1!==a.indexOf(b+"\x3d")?a:a+(-1!==a.indexOf("?")?"\x26":"?")+b+"\x3d"+encodeURIComponent(c)}
var loadAccountLayer=!0,headerItemAccount=document.getElementById("header-item-account"),headerLinkText=headerItemAccount?headerItemAccount.getElementsByClassName("header-link-text")[0]:null,headerLink=headerItemAccount?headerItemAccount.getElementsByClassName("header-link")[0]:null;
if(headerLinkText&&headerLink)if(User.CustomerId){var userFirstName=getCookie("fname"),headerwelcome="";userFirstName&&(userFirstName=10>(userFirstName=decodeURIComponent(userFirstName)).length?Resources.ACCOUNT_HEADER_WELCOME.replace("{0}",userFirstName):userFirstName.substring(0,20),headerLinkText.textContent=userFirstName);headerLink.setAttribute("href",Urls.showAccount)}else headerLinkText.textContent=Resources.ACCOUNT_HEADER_TITLE,headerLink.setAttribute("href",Urls.showLogin);
document.addEventListener("DOMContentLoaded",function(){$("#header-item-account").hover(function(a){a.preventDefault();loadAccountLayer&&(loadAccountLayer=!1,$(".account-layer.header-layer-content").load(Urls.headerAccountLayer,function(){var a=$("#header-item-account").find(".left-side");$(this).find("img[data-src].lazy-image").each(function(){var a=$(this);null!=a.data("src")&&a.attr("src",a.data("src"));a.one("load",function(){this.style.opacity=1})});$(".last-order-details").length?a.addClass("with-last-order"):
a.removeClass("with-last-order")}))})});var loadStoreLayer=!0,storeHeaderItem=document.getElementById("header-item-storelocator"),storeHeaderText=storeHeaderItem?storeHeaderItem.getElementsByClassName("header-link-text")[0]:null,headerLinkWrapper=storeHeaderItem?storeHeaderItem.getElementsByClassName("header-link-wrapper")[0]:null;
if(storeHeaderText&&headerLinkWrapper)if(User.CustomerId){var favStoreDetails=getCookie("favStore");if(favStoreDetails){var favStoreDetails=decodeURIComponent(favStoreDetails),storeId=(favStoreDetails=JSON.parse(favStoreDetails)).id,storeName=favStoreDetails.name,storeStatus=favStoreDetails.status,storeMessage=favStoreDetails.message;if(storeStatus&&(headerLinkWrapper.className+=" store favorite-store "+storeStatus),storeId&&headerLinkWrapper.setAttribute("data-store-id",storeId),storeName){var favoriteStoreName=
document.createElement("span");favoriteStoreName.className="favorite-store-name";favoriteStoreName.innerHTML=storeName;storeHeaderText.appendChild(favoriteStoreName);storeHeaderText.style.display=""}storeMessage&&((storeStatus=document.createElement("span")).className="store-working-status-block",storeStatus.innerHTML=storeMessage,storeHeaderText.appendChild(storeStatus),storeHeaderText.style.display="")}else storeHeaderText.textContent=Resources.HEADER_STORES_TEXT}else storeHeaderText.textContent=
Resources.HEADER_STORES_TEXT;document.addEventListener("DOMContentLoaded",function(){$("#header-item-storelocator").hover(function(a){a.preventDefault();loadStoreLayer&&(loadStoreLayer=!1,$.ajax({url:appendParamToURL(Urls.getStorelocatorHeaderItem,"hideHeader",!0),success:function(a){loadGoogleMaps();a&&$(".header-layer-content.store-content").replaceWith(a)}}))})});
document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("header-item-minicart"),b=document.getElementsByClassName("mobile-header")[0],c=b?b.getElementsByClassName("top-right")[0]:null,d=document.getElementsByClassName("desktop-header")[0];a&&c&&d&&(window.matchMedia("(max-width: 1023px)").matches&&c.appendChild(a),window.onresize=function(){window.matchMedia("(max-width: 1023px)").matches?c.appendChild(a):d.getElementsByClassName("header-links")[0].appendChild(a)})});